// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijmjwqkyrrmbfmnbmgur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbWp3cWt5cnJtYmZtbmJtZ3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODU5NTYsImV4cCI6MjA3MzM2MTk1Nn0.gr6EzIGFN5jRcb53NQLvEMpKma8WCw3fe5360_LvZWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});